# Generated by Django 5.1.6 on 2025-03-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('student_id', models.CharField(max_length=10)),
                ('department', models.IntegerField(choices=[(1, 'Bilişim Sistemleri Ve Teknolojileri'), (2, 'Bankacılık Ve Sigortacılık'), (3, 'Halkla İlişkiler Ve Reklamcılık'), (4, 'Gümrük İşletme'), (5, 'Uluslararası Ticaret Ve Finansman'), (6, 'Diğer')], default=6)),
                ('qr_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('is_joined', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(null=True)),
                ('leave_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
