# Generated by Django 5.1.7 on 2026-04-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_joined',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='leave_date',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Yoklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oturum', models.IntegerField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etkinlik.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'oturum')},
            },
        ),
    ]
