# Generated by Django 5.1.6 on 2025-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0002_alter_ticket_email_alter_ticket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.IntegerField(choices=[(1, 'Bilişim Sistemleri Ve Teknolojileri'), (2, 'Bankacılık Ve Sigortacılık'), (3, 'Halkla İlişkiler Ve Reklamcılık'), (4, 'Gümrük İşletme'), (5, 'Uluslararası Ticaret Ve Finansman'), (6, 'Diğer')], default=6),
        ),
    ]
