# Generated by Django 5.1.7 on 2026-04-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0002_remove_ticket_entry_date_remove_ticket_is_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktifOturum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oturum', models.IntegerField(default=1)),
            ],
        ),
    ]
