# Generated by Django 5.1.6 on 2025-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etkinlik', '0003_alter_ticket_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='entry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='leave_date',
            field=models.DateTimeField(null=True),
        ),
    ]
